=== MartinC1996/SIPVS/src/main/resource/xml/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Applications">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element name="Application" type="application"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="application">
		<xs:sequence>
			<xs:element name="CourseTitle" type="xs:string"/>
			<xs:element name="CourseRoom" type="xs:string"/>
			<xs:element name="CourseDate" type="xs:date"/>
			<xs:element name="CourseTime" type="xs:time"/>
			<xs:element name="CourseNewbie" type="xs:boolean"/>
			<xs:element name="CourseLessons" type="xs:integer"/>
			<xs:element name="Students" type="students"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="students">
		<xs:sequence minOccurs="0" maxOccurs="30">
			<xs:element name="Student" type="student"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="student">
		<xs:sequence>
			<xs:element name="StudentFirstName" type="xs:string"/>
			<xs:element name="StudentLastName" type="xs:string"/>
			<xs:element name="StudentMobile" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" use="required"/>
	</xs:complexType>
	
</xs:schema>

=== MartinC1996/SIPVS/src/main/resource/xml/sample2.xml
<?xml version="1.0" encoding="UTF-8"?><tt:Application xmlns:tt="http://www.example.org/sipvs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/sipvs schema.xsd"><tt:CourseTitle>Roki</tt:CourseTitle><tt:CourseRoom>Room24</tt:CourseRoom><tt:CourseDate>2019-11-18</tt:CourseDate><tt:CourseTime>21:00:00</tt:CourseTime><tt:CourseNewbie>false</tt:CourseNewbie><tt:CourseLessons>1</tt:CourseLessons><tt:Students><tt:Student id="1"><tt:StudentFirstName>Tera</tt:StudentFirstName><tt:StudentLastName>Nova</tt:StudentLastName><tt:StudentMobile>45645645</tt:StudentMobile></tt:Student><tt:Student id="2"><tt:StudentFirstName>Digitus</tt:StudentFirstName><tt:StudentLastName>Digito</tt:StudentLastName><tt:StudentMobile>45645645</tt:StudentMobile></tt:Student></tt:Students></tt:Application>
